"use client";
import React, { useState, useEffect } from "react";
import type { Shipment, Role } from "../page";

const API_BASE_ROUTES = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

interface GraphNode {
    code: string;
    name: string;
}

interface ReceiverUser {
    user_id: string;
    username: string;
    email: string;
}

interface Props {
    shipments: Shipment[];
    selectedShipment: Shipment | null;
    onSelect: (s: Shipment) => void;
    onCreated: () => void;
    apiBase: string;
    role: Role;
    token: string | null;
}

const statusColors: Record<string, string> = {
    created: "var(--accent-blue)",
    in_transit: "var(--accent-amber)",
    delivered: "var(--accent-green)",
    anomaly: "var(--accent-red)",
};

export default function ShipmentPanel({
    shipments,
    selectedShipment,
    onSelect,
    onCreated,
    apiBase,
    role,
    token,
}: Props) {
    const [showCreate, setShowCreate] = useState(false);
    const [creating, setCreating] = useState(false);
    const [availableNodes, setAvailableNodes] = useState<GraphNode[]>([]);
    const [receivers, setReceivers] = useState<ReceiverUser[]>([]);
    const [form, setForm] = useState({
        shipment_id: "",
        origin: "",
        destination: "",
        receiver_id: "",
        po_text: "",
        invoice_text: "",
        bol_text: "",
    });

    useEffect(() => {
        fetch(`${API_BASE_ROUTES}/routes/nodes`)
            .then((r) => r.json())
            .then(setAvailableNodes)
            .catch(() => { });
        fetch(`${API_BASE_ROUTES}/auth/users/receivers`)
            .then((r) => r.json())
            .then(setReceivers)
            .catch(() => { });
    }, []);

    const handleCreate = async () => {
        if (!form.shipment_id || !form.origin || !form.destination || !form.receiver_id) return;
        setCreating(true);
        try {
            const body = {
                shipment_id: form.shipment_id,
                origin: form.origin,
                destination: form.destination,
                receiver_id: form.receiver_id,
                route: [], // Auto-generated by backend
                ...(form.po_text && { po_text: form.po_text }),
                ...(form.invoice_text && { invoice_text: form.invoice_text }),
                ...(form.bol_text && { bol_text: form.bol_text }),
            };
            const res = await fetch(`${apiBase}/shipments/`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    ...(token ? { Authorization: `Bearer ${token}` } : {}),
                },
                body: JSON.stringify(body),
            });
            if (res.ok) {
                setShowCreate(false);
                setForm({
                    shipment_id: "",
                    origin: "",
                    destination: "",
                    receiver_id: "",
                    po_text: "",
                    invoice_text: "",
                    bol_text: "",
                });
                onCreated();
            } else {
                const err = await res.json();
                alert(err.detail || "Failed to create shipment");
            }
        } catch (e) {
            console.error("Create shipment error:", e);
        }
        setCreating(false);
    };

    const cardStyle: React.CSSProperties = {
        background: "var(--bg-card)",
        borderRadius: "var(--radius)",
        border: "1px solid var(--border-color)",
        padding: "20px",
        boxShadow: "var(--shadow-card)",
    };

    const inputStyle: React.CSSProperties = {
        width: "100%",
        padding: "10px 14px",
        borderRadius: "var(--radius-sm)",
        border: "1px solid var(--border-color)",
        background: "var(--bg-secondary)",
        color: "var(--text-primary)",
        fontSize: "14px",
        outline: "none",
        transition: "border-color 0.2s",
    };

    const selectStyle: React.CSSProperties = {
        ...inputStyle,
        appearance: "none" as const,
        backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%2394a3b8' d='M6 8L1 3h10z'/%3E%3C/svg%3E")`,
        backgroundRepeat: "no-repeat",
        backgroundPosition: "right 12px center",
        paddingRight: "32px",
    };

    return (
        <div style={cardStyle}>
            <div
                style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    marginBottom: "16px",
                }}
            >
                <h2
                    style={{
                        fontSize: "16px", fontWeight: 700,
                        color: "var(--text-primary)", margin: 0,
                        display: "flex", alignItems: "center", gap: "8px",
                    }}
                >
                    📋 {role === "receiver" ? "Assigned Shipments" : role === "transit_node" ? "Shipments at My Nodes" : "Active Shipments"}
                    <span
                        style={{
                            fontSize: "12px", fontWeight: 500,
                            padding: "2px 8px", borderRadius: "12px",
                            background: "var(--bg-elevated)", color: "var(--text-muted)",
                        }}
                    >
                        {shipments.length}
                    </span>
                </h2>
                {role === "manufacturer" && (
                    <button
                        id="create-shipment-btn"
                        onClick={() => setShowCreate(!showCreate)}
                        style={{
                            padding: "8px 16px", borderRadius: "var(--radius-sm)",
                            border: "none", background: "var(--gradient-primary)",
                            color: "white", fontSize: "13px", fontWeight: 600,
                            cursor: "pointer", transition: "transform 0.15s, box-shadow 0.15s",
                        }}
                    >
                        + New Shipment
                    </button>
                )}
            </div>

            {/* Create Form */}
            {showCreate && (
                <div
                    className="animate-fade-in"
                    style={{
                        background: "var(--bg-secondary)", borderRadius: "var(--radius-sm)",
                        padding: "16px", marginBottom: "16px",
                        border: "1px solid var(--border-color)",
                    }}
                >
                    {/* Row 1: ID + Receiver */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", marginBottom: "12px" }}>
                        <div>
                            <label style={{ fontSize: "11px", fontWeight: 500, color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Shipment ID</label>
                            <input
                                id="input-shipment-id"
                                style={inputStyle}
                                placeholder="e.g. SHIP-001"
                                value={form.shipment_id}
                                onChange={(e) => setForm({ ...form, shipment_id: e.target.value })}
                            />
                        </div>
                        <div>
                            <label style={{ fontSize: "11px", fontWeight: 500, color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Receiver</label>
                            <select
                                style={selectStyle}
                                value={form.receiver_id}
                                onChange={(e) => setForm({ ...form, receiver_id: e.target.value })}
                            >
                                <option value="">Select receiver...</option>
                                {receivers.map((r) => (
                                    <option key={r.user_id} value={r.user_id}>
                                        {r.username} ({r.email})
                                    </option>
                                ))}
                            </select>
                        </div>
                    </div>

                    {/* Row 2: Origin + Destination (from node graph) */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px", marginBottom: "12px" }}>
                        <div>
                            <label style={{ fontSize: "11px", fontWeight: 500, color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Origin Node</label>
                            <select
                                id="input-origin"
                                style={selectStyle}
                                value={form.origin}
                                onChange={(e) => setForm({ ...form, origin: e.target.value })}
                            >
                                <option value="">Select origin...</option>
                                {availableNodes.map((n) => (
                                    <option key={n.code} value={n.code}>
                                        {n.code} — {n.name}
                                    </option>
                                ))}
                            </select>
                        </div>
                        <div>
                            <label style={{ fontSize: "11px", fontWeight: 500, color: "var(--text-muted)", display: "block", marginBottom: "4px" }}>Destination Node</label>
                            <select
                                id="input-destination"
                                style={selectStyle}
                                value={form.destination}
                                onChange={(e) => setForm({ ...form, destination: e.target.value })}
                            >
                                <option value="">Select destination...</option>
                                {availableNodes.filter((n) => n.code !== form.origin).map((n) => (
                                    <option key={n.code} value={n.code}>
                                        {n.code} — {n.name}
                                    </option>
                                ))}
                            </select>
                        </div>
                    </div>

                    {/* Row 3: Documents (optional) */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "12px", marginBottom: "12px" }}>
                        <textarea
                            style={{ ...inputStyle, minHeight: "70px", resize: "vertical" }}
                            placeholder="PO text (optional)"
                            value={form.po_text}
                            onChange={(e) => setForm({ ...form, po_text: e.target.value })}
                        />
                        <textarea
                            style={{ ...inputStyle, minHeight: "70px", resize: "vertical" }}
                            placeholder="Invoice text (optional)"
                            value={form.invoice_text}
                            onChange={(e) => setForm({ ...form, invoice_text: e.target.value })}
                        />
                        <textarea
                            style={{ ...inputStyle, minHeight: "70px", resize: "vertical" }}
                            placeholder="BOL text (optional)"
                            value={form.bol_text}
                            onChange={(e) => setForm({ ...form, bol_text: e.target.value })}
                        />
                    </div>

                    {/* Route preview */}
                    {form.origin && form.destination && (
                        <div style={{ marginBottom: "12px", padding: "8px 12px", borderRadius: "6px", background: "var(--bg-card)", fontSize: "12px", color: "var(--accent-cyan)" }}>
                            🔀 Optimal route will be auto-generated from <strong>{form.origin}</strong> → <strong>{form.destination}</strong>
                        </div>
                    )}

                    <button
                        id="submit-shipment-btn"
                        onClick={handleCreate}
                        disabled={creating || !form.shipment_id || !form.origin || !form.destination || !form.receiver_id}
                        style={{
                            padding: "10px 24px", borderRadius: "var(--radius-sm)",
                            border: "none",
                            background: creating ? "var(--text-muted)" : "var(--gradient-success)",
                            color: "white", fontSize: "14px", fontWeight: 600,
                            cursor: creating ? "not-allowed" : "pointer",
                        }}
                    >
                        {creating ? "Creating..." : "🚀 Create Shipment"}
                    </button>
                </div>
            )}

            {/* Shipment List */}
            <div style={{ display: "flex", flexDirection: "column", gap: "8px", maxHeight: "400px", overflowY: "auto" }}>
                {shipments.length === 0 && (
                    <p style={{ color: "var(--text-muted)", textAlign: "center", padding: "32px", fontSize: "14px" }}>
                        {role === "manufacturer" ? "No shipments yet. Create one to get started!" :
                            role === "receiver" ? "No shipments assigned to you yet." :
                                "No shipments passing through your nodes."}
                    </p>
                )}
                {shipments.map((s) => (
                    <button
                        key={s.shipment_id}
                        onClick={() => onSelect(s)}
                        style={{
                            display: "flex", alignItems: "center", justifyContent: "space-between",
                            padding: "12px 16px", borderRadius: "var(--radius-sm)",
                            border: selectedShipment?.shipment_id === s.shipment_id
                                ? "1px solid var(--accent-blue)" : "1px solid transparent",
                            background: selectedShipment?.shipment_id === s.shipment_id
                                ? "var(--bg-elevated)" : "transparent",
                            cursor: "pointer", transition: "all 0.15s", textAlign: "left",
                            width: "100%", color: "var(--text-primary)",
                        }}
                    >
                        <div>
                            <span style={{ fontWeight: 600, fontSize: "14px" }}>{s.shipment_id}</span>
                            <span style={{ fontSize: "12px", color: "var(--text-muted)", marginLeft: "12px" }}>
                                {s.origin} → {s.destination}
                            </span>
                        </div>
                        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                            {s.risk_profile?.product_category && (
                                <span
                                    style={{
                                        fontSize: "11px", padding: "2px 8px", borderRadius: "12px",
                                        background: "var(--bg-secondary)", color: "var(--accent-cyan)", fontWeight: 500,
                                    }}
                                >
                                    {s.risk_profile.product_category}
                                </span>
                            )}
                            <span
                                style={{
                                    width: 8, height: 8, borderRadius: "50%",
                                    background: statusColors[s.current_status] || "var(--text-muted)",
                                }}
                            />
                        </div>
                    </button>
                ))}
            </div>
        </div>
    );
}
